name: Bug report
description: Report a problem with a profile, script, or docs
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug! Please include enough detail to reproduce.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? What did you expect?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: VS Code version
      placeholder: 1.XX.X
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14.x / Ubuntu 22.04 / Windows 11
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run scripts/compose-settings.sh
        2. Open profile web-astro-crisp
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/output
      description: Relevant command or extension output (redact secrets)
      render: shell

